# Default Configuration for Parkinson's Disease Detection
# This file defines all configurable parameters for the ML pipeline

# Data Configuration
data:
  path: "parkinsons.data"
  target_column: "status"
  subject_id_column: "subject_id"
  feature_columns: null  # Will be auto-detected (all except name, status, subject_id)
  
# Cross-Validation Configuration
cross_validation:
  strategy: "StratifiedGroupKFold"
  n_splits: 10
  shuffle: true
  random_state: 42
  test_size: 0.2  # For train_test_split if needed

# Model Configuration
model:
  algorithm: "RandomForest"
  parameters:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2
    min_samples_leaf: 1
    random_state: 42
    class_weight: "balanced"
    n_jobs: -1

# Preprocessing Configuration
preprocessing:
  scaler: "StandardScaler"  # StandardScaler, MinMaxScaler, RobustScaler
  handle_missing: "drop"    # drop, impute_mean, impute_median
  feature_selection: null   # null, mutual_info, chi2, f_classif
  n_features: null          # Number of features to select (null = all)

# Evaluation Configuration
evaluation:
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1"
    - "roc_auc"
  clinical_metrics: true
  feature_importance: true
  confusion_matrix: true
  roc_curve: true
  learning_curves: false

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  file: "parkinsons_analysis.log"
  console: true
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Output Configuration
output:
  results_dir: "results"
  models_dir: "models"
  plots_dir: "plots"
  reports_dir: "reports"
  save_model: true
  save_predictions: true
  save_plots: true
