# Random Forest Configuration: 200 trees, 3-fold CV
# More trees for potential better performance

# Data Configuration
data:
  path: "parkinsons.data"
  target_column: "status"
  subject_id_column: "subject_id"
  
# Cross-Validation Configuration
cross_validation:
  strategy: "StratifiedGroupKFold"
  n_splits: 3
  shuffle: true
  random_state: 42

# Model Configuration
model:
  algorithm: "RandomForest"
  parameters:
    n_estimators: 200
    max_depth: 10
    min_samples_split: 2
    min_samples_leaf: 1
    random_state: 42
    class_weight: "balanced"
    n_jobs: -1

# Preprocessing Configuration
preprocessing:
  scaler: "StandardScaler"
  handle_missing: "drop"
  feature_selection: null

# Evaluation Configuration
evaluation:
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1"
    - "roc_auc"
  clinical_metrics: true
  feature_importance: true
  confusion_matrix: true
  roc_curve: true

# Logging Configuration
logging:
  level: "INFO"
  file: "parkinsons_analysis.log"
  console: true

# Output Configuration
output:
  results_dir: "results"
  models_dir: "models"
  plots_dir: "plots"
  reports_dir: "reports"
  save_model: true
  save_predictions: true
  save_plots: true
